#spring.application.name=Keyclock
#server.port=8090
server:
  port: 8081
jwt:
  auth:
    converter:
      resource-id: saad-rest-api
      principle-attributes: preferred_username


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Saad
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs